# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 316350fa68a831c41dfea4fce3380497c0f345dfdae81b8c0d946d2b8c07b7464c360e2dc7fb8bd70bf1febd939275f66beb26d9aa0d196558988d9c3fc06029

test:
  secret_key_base: 64adc9f0a4f658fca6966aeb15acaf4e15fa383f8208d13f873d67e14537a924865d63c9dcee29b62704cf3470ca3acccf81e8c0a7cf2db8d89bd9b6d92c9c92

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
